### ISSUE TITLE
GPU monitoring

### ISSUE THREAD

**Issue by Hunter23071985** [Zerogate309/Rainmeter-Skin_Hex-H#2]
[This skin](https://www.deviantart.com/zawawawa/art/Illyasviel-von-Einzbern-Rainmeter-Skin-870372494) implements GPU load monitor.
This is important information. Can you add it to Hex-H?
Sincerely.

**Comment by Zerogate309** [comment]
GPU measures is not a Part of Rainmeter. you must implement it with an external dll-File.
So far i know, is there only a dll-file for MSI-GPUs.
The Problem is: I teach myself everything by reverse engineering! So i must see, how an other Rainmeter Skin works and then i can try to code...
I planed, for the next Version of my Skin, to implement the Plugin for HWiNFO!
Then you can have much more important Informations you wanna have!
Sincerely.

**Comment by Hunter23071985** [comment]
External DLLs and HWiNFO are not needed by anyone.
- Try UsageMonitor plugin instead of external DLL:
see how works the [skin](https://www.deviantart.com/zawawawa/art/Illyasviel-von-Einzbern-Rainmeter-Skin-870372494) I linked above and [docs](https://docs.rainmeter.net/manual/plugins/usagemonitor).
- Сompare [illustro Pulsar](https://www.deviantart.com/pul53dr1v3r/art/Rainformer-2-9-3-AIDA64-Edition-Rainmeter-444287665) AIDA64 and HWiNFO Edition:
instead of HWiNFO, CoreTemp, SpeedFan and others combined, there is one AIDA64.
